"""Mock attestation report generation for Phase 2 POC.

This module simulates Azure Confidential Computing attestation reports.
In a real deployment, these would be generated by actual TEE hardware.

The attestation report cryptographically binds:
- The build runner code (launch measurement)
- The passport document (via hash in custom data)
- Freshness/replay protection (via nonce in custom data)
"""

import hashlib
import json
import secrets
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import NamedTuple


class AttestationReport(NamedTuple):
    """Mock attestation report matching Azure TEE format."""
    report_id: str
    timestamp: str
    launch_measurement: str
    custom_data: str  # Hex-encoded 64 bytes
    passport_hash: str  # First 32 bytes of custom_data
    nonce: str  # Last 32 bytes of custom_data
    signature: str  # Mock signature
    platform_info: dict


def generate_nonce() -> bytes:
    """Generate a 32-byte nonce for replay protection.

    For POC, uses timestamp-based approach (simpler than challenge-response).

    Returns:
        32 bytes of random data
    """
    # Mix timestamp with random bytes for POC
    timestamp_bytes = int(datetime.now(timezone.utc).timestamp()).to_bytes(8, 'big')
    random_bytes = secrets.token_bytes(24)
    return timestamp_bytes + random_bytes


def create_custom_data(passport: dict, nonce: bytes | None = None) -> tuple[bytes, str, str]:
    """Create 64-byte custom data for attestation report.

    Format (as specified in plan.md):
    - Bytes 0-31: SHA256(passport JSON)
    - Bytes 32-63: Nonce (32 bytes for replay protection)

    Args:
        passport: Passport dictionary to hash
        nonce: Optional 32-byte nonce. If None, generates a new one.

    Returns:
        Tuple of (custom_data_bytes, passport_hash_hex, nonce_hex)
    """
    if nonce is None:
        nonce = generate_nonce()

    if len(nonce) != 32:
        raise ValueError("Nonce must be exactly 32 bytes")

    # Hash the passport (canonical JSON for determinism)
    passport_json = json.dumps(passport, sort_keys=True, separators=(',', ':'))
    passport_hash = hashlib.sha256(passport_json.encode()).digest()

    # Combine: passport_hash (32 bytes) + nonce (32 bytes) = 64 bytes
    custom_data = passport_hash + nonce

    return custom_data, passport_hash.hex(), nonce.hex()


def generate_mock_signature(data_to_sign: dict) -> str:
    """Generate a mock signature for attestation report.

    In a real TEE, this would be signed by hardware-protected keys.
    For POC, we create a deterministic hash.

    Args:
        data_to_sign: Dictionary of data to include in signature

    Returns:
        Hex-encoded mock signature
    """
    # Create deterministic signature based on data
    data_json = json.dumps(data_to_sign, sort_keys=True)
    signature = hashlib.sha256(data_json.encode()).digest()

    # In real attestation, this would be an RSA/ECDSA signature
    # For POC, we'll use a hash with a prefix to indicate it's mock
    return f"MOCK_SIG_{signature.hex()}"


def create_attestation_report(
    launch_measurement: str,
    passport: dict,
    nonce: bytes | None = None,
    output_path: Path | None = None,
) -> AttestationReport:
    """Generate a mock attestation report for the build.

    Args:
        launch_measurement: Hash of the TEE build runner code (golden measurement)
        passport: Passport document to bind to attestation
        nonce: Optional nonce for replay protection (generated if not provided)
        output_path: Optional path to write attestation JSON

    Returns:
        AttestationReport with all attestation data
    """
    # Generate custom data
    custom_data_bytes, passport_hash, nonce_hex = create_custom_data(passport, nonce)

    # Create report metadata
    report_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Platform information (mock for POC)
    platform_info = {
        "tee_type": "Azure_CVM_SEV_SNP",  # AMD SEV-SNP example
        "tee_version": "1.51",
        "platform_status": "UpToDate",
        "note": "MOCK_ATTESTATION_POC",
    }

    # Create signature over all data
    data_to_sign = {
        "report_id": report_id,
        "timestamp": timestamp,
        "launch_measurement": launch_measurement,
        "custom_data": custom_data_bytes.hex(),
        "platform_info": platform_info,
    }
    signature = generate_mock_signature(data_to_sign)

    report = AttestationReport(
        report_id=report_id,
        timestamp=timestamp,
        launch_measurement=launch_measurement,
        custom_data=custom_data_bytes.hex(),
        passport_hash=passport_hash,
        nonce=nonce_hex,
        signature=signature,
        platform_info=platform_info,
    )

    # Write to file if requested
    if output_path:
        report_dict = {
            "report_id": report.report_id,
            "timestamp": report.timestamp,
            "launch_measurement": report.launch_measurement,
            "custom_data": report.custom_data,
            "signature": report.signature,
            "platform_info": report.platform_info,
            "verification_notes": {
                "passport_hash": report.passport_hash,
                "nonce": report.nonce,
                "description": "Custom data is 64 bytes: passport_hash (32 bytes) + nonce (32 bytes)",
            },
        }
        output_path.write_text(json.dumps(report_dict, indent=2))

    return report


def verify_attestation_binding(
    attestation: AttestationReport,
    passport: dict,
) -> tuple[bool, str]:
    """Verify that an attestation report is bound to a passport.

    This checks that the passport hash in the attestation custom data
    matches the actual passport document.

    Args:
        attestation: Attestation report to verify
        passport: Passport document to check

    Returns:
        Tuple of (verified, message)
    """
    # Extract passport hash from custom data (first 32 bytes / 64 hex chars)
    custom_data_bytes = bytes.fromhex(attestation.custom_data)
    if len(custom_data_bytes) != 64:
        return False, f"Invalid custom data length: {len(custom_data_bytes)} (expected 64 bytes)"

    attestation_passport_hash = custom_data_bytes[:32].hex()

    # Hash the actual passport
    passport_json = json.dumps(passport, sort_keys=True, separators=(',', ':'))
    actual_passport_hash = hashlib.sha256(passport_json.encode()).hexdigest()

    if attestation_passport_hash != actual_passport_hash:
        return False, f"Passport hash mismatch: {attestation_passport_hash[:16]}... != {actual_passport_hash[:16]}..."

    return True, "Attestation is correctly bound to passport"


def verify_nonce_freshness(
    nonce_hex: str,
    max_age_seconds: int = 300,
) -> tuple[bool, str]:
    """Verify that a nonce is fresh (timestamp-based approach for POC).

    Args:
        nonce_hex: Hex-encoded nonce to check
        max_age_seconds: Maximum age in seconds (default 5 minutes)

    Returns:
        Tuple of (verified, message)
    """
    try:
        nonce_bytes = bytes.fromhex(nonce_hex)
        if len(nonce_bytes) != 32:
            return False, f"Invalid nonce length: {len(nonce_bytes)} (expected 32 bytes)"

        # Extract timestamp from first 8 bytes
        timestamp_bytes = nonce_bytes[:8]
        nonce_timestamp = int.from_bytes(timestamp_bytes, 'big')
        current_timestamp = int(datetime.now(timezone.utc).timestamp())

        age = current_timestamp - nonce_timestamp
        if age > max_age_seconds:
            return False, f"Nonce is too old: {age} seconds (max {max_age_seconds})"

        if age < 0:
            return False, "Nonce timestamp is in the future"

        return True, f"Nonce is fresh: {age} seconds old"

    except Exception as e:
        return False, f"Error verifying nonce: {e}"
