name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans sources
    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Install cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check ${{ matrix.checks }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Run linters
        run: ./bin/lint

  run-tests:
    name: Run tests
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-15-intel # mac-x86
          - macos-latest # mac-arm
          - ubuntu-latest # linux-x86
          - ubuntu-24.04-arm # linux-arm

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@nextest
      - name: Run non-TEE tests
        shell: bash
        run: ./bin/test

  build-projects:
    name: Build ${{ matrix.project }} with Kettle
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        - project: ripgrep
          owner: burntsushi
          toolchain: cargo
        - project: eza
          owner: eza-community
          toolchain: nix
        - project: openclaw
          owner: openclaw
          toolchain: pnpm
    steps:
      - uses: actions/checkout@v6
      - name: Clone target project # Must match DIR in bin/kettle-build
        run: git clone "https://github.com/${{ matrix.owner }}/${{ matrix.project }}" "/tmp/${{ matrix.project }}"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        if: matrix.toolchain == 'cargo'
        working-directory: "/tmp/${{ matrix.project }}"
      - uses: cachix/install-nix-action@v31
        if: matrix.toolchain == 'nix'
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup pnpm
        if: matrix.toolchain == 'pnpm'
        working-directory: "/tmp/${{ matrix.project }}"
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        if: matrix.toolchain == 'pnpm'
        working-directory: "/tmp/${{ matrix.project }}"
        uses: actions/setup-node@v4
      - run: bin/kettle-build ${{ matrix.project }}
